// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymykorlcgdpzszjsfntb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteWtvcmxjZ2RwenN6anNmbnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Nzc2MzIsImV4cCI6MjA2ODM1MzYzMn0.L2n9yn7_MTf3dqqWrZInvTu7wupeSOWlE4XG3cTlr-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});